[package]
name = "mal-rust"
version = "0.1.0"
authors = ["CodeIsLove"]

[dependencies]
regex = "1.7.0"
lazy_static = "1.4.0"
rustyline = "10.0.0"
im-rc = "15.1.0"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_error"] }
env_logger = "0.10.0"